INSERT INTO producto (nombre, descrip, precio, stock, activo) VALUES
   ('Torta Tres Leches', 'Bizcocho empapado en tres tipos de leche, cubierto con merengue', 25.00, 30, true),
    ('Tiramisú Clásico', 'Postre italiano con capas de bizcochos de soletilla, café y crema de mascarpone', 20.00, 25, true),
    ('Torta Selva Negra', 'Bizcocho de chocolate, crema chantilly, cerezas y virutas de chocolate', 28.00, 20, true),
   ('Cheesecake de Oreo', 'Base de galleta Oreo, relleno cremoso de queso y trozos de Oreo', 22.00, 35, true),
   ('Brownie de Chocolate', 'Intenso bizcocho de chocolate con nueces', 5.50, 100, true),
   ('Cupcakes de Vainilla', 'Bizcochitos individuales de vainilla con frosting', 3.00, 150, true),
   ('Macarons Surtidos', 'Delicados dulces franceses de almendra en varios sabores', 2.50, 200, true),
   ('Pie de Limón', 'Base de galleta, crema de limón ácida y merengue tostado', 18.00, 28, true),
   ('Galletas de Mantequilla', 'Clásicas galletas crujientes de mantequilla', 1.50, 300, true),
   ('Donas Glaseadas', 'Donas esponjosas cubiertas con glaseado dulce', 2.00, 180, true),
   ('Profiteroles con Crema', 'Pequeños bocadillos de pasta choux rellenos de crema pastelera', 7.00, 90, true),
   ('Mousse de Maracuyá', 'Postre ligero y aireado con sabor tropical a maracuyá', 6.50, 70, true),
   ('Volcán de Chocolate', 'Bizcocho de chocolate con centro líquido', 8.00, 60, true),
   ('Eclairs de Café', 'Pastelitos alargados de pasta choux rellenos de crema de café', 4.00, 110, true),
   ('Tartaleta de Frutas', 'Base de masa quebrada con crema pastelera y frutas frescas', 7.50, 80, true),
   ('Alfajores de Maicena', 'Galletas suaves unidas con dulce de leche y coco rallado', 2.20, 160, true),
   ('Brazo de Gitano', 'Bizcocho enrollado relleno de crema o mermelada', 15.00, 22, true),
   ('Panna Cotta de Frutos Rojos', 'Postre cremoso italiano con salsa de frutos rojos', 6.00, 75, true),
   ('Crumble de Manzana', 'Manzanas horneadas cubiertas con una capa crujiente de avena', 9.00, 45, true),
   ('Trufas de Chocolate', 'Pequeñas bolitas de chocolate intenso', 1.80, 250, true),
   ('Pastel Red Velvet', 'Pastel de terciopelo rojo con glaseado de queso crema', 26.00, 28, true),
   ('Muffins de Arándanos', 'Muffins suaves con arándanos frescos', 3.20, 130, true),
   ('Rollos de Canela', 'Panecillos dulces con canela y glaseado', 3.50, 100, true),
   ('Flan Casero', 'Postre de huevo y leche con caramelo', 5.00, 95, true),
   ('Gelatina de Mosaico', 'Gelatina de varios sabores cortada en cubos y unida con gelatina de leche', 4.50, 85, true),
   ('Milhojas con Dulce de Leche', 'Capas de hojaldre crujiente y dulce de leche', 12.00, 40, true),
   ('Churros con Chocolate', 'Masa frita crujiente acompañada de chocolate caliente', 6.00, 120, true),
   ('Tarta de Santiago', 'Tarta tradicional de almendras de origen español', 19.00, 20, true),
   ('Pastel de Zanahoria', 'Bizcocho húmedo de zanahoria con glaseado de queso crema', 24.00, 30, true),
   ('Rollos de Guayaba', 'Dulce de guayaba enrollado en masa suave', 4.00, 90, true),
   ('Cocadas', 'Dulces de coco rallado y azúcar horneados', 2.00, 150, true),
   ('Mazapán', 'Dulce tradicional a base de almendras y azúcar', 3.00, 100, true),
   ('Panellets', 'Pequeños dulces de almendra y piñones, típicos de Cataluña', 2.80, 80, true),
   ('Buñuelos de Viento', 'Bollos fritos ligeros y esponjosos, a menudo rellenos', 3.50, 110, true),
   ('Torrijas', 'Rebanadas de pan empapadas en leche y huevo, fritas y endulzadas', 4.50, 70, true);