import type { Producto } from '../interface/interfaceProduct';



export const productosMockUp: Producto[] = [
  {
    id_producto: 1,
    nombre: 'Pastel de Chocolate',
    descrip: 'Delicioso pastel de chocolate con cobertura de fudge.',
    precio: 25.0,
    stock: 15,
    activo: true,
    createdAt: '2025-11-09T10:00:00Z',
  },
  {
    id_producto: 2,
    nombre: 'Galletas con Chispas de Chocolate',
    descrip: 'Galletas caseras recién horneadas.',
    precio: 1.5,
    stock: 100,
    activo: true,
    createdAt: '2025-11-09T10:05:00Z',
  },
  {
    id_producto: 3,
    nombre: 'Cheesecake de Fresa',
    descrip: 'Cremoso cheesecake con mermelada de fresa.',
    precio: 30.0,
    stock: 10,
    activo: true,
    createdAt: '2025-11-09T10:10:00Z',
  },
  {
    id_producto: 4,
    nombre: 'Cupcakes de Vainilla',
    descrip: 'Cupcakes esponjosos con betún de vainilla.',
    precio: 2.5,
    stock: 50,
    activo: true,
    createdAt: '2025-11-09T10:15:00Z',
  },
  {
    id_producto: 5,
    nombre: 'Macarons Surtidos',
    descrip: 'Caja de 6 macarons de diferentes sabores.',
    precio: 12.0,
    stock: 40,
    activo: true,
    createdAt: '2025-11-09T10:20:00Z',
  },
  {
    id_producto: 6,
    nombre: 'Tarta de Manzana',
    descrip: 'Tarta clásica de manzana con canela.',
    precio: 20.0,
    stock: 20,
    activo: false,
    createdAt: '2025-11-09T10:25:00Z',
  },
  {
    id_producto: 7,
    nombre: 'Brownies de Nuez',
    descrip: 'Brownies de chocolate densos con nueces.',
    precio: 3.0,
    stock: 60,
    activo: true,
    createdAt: '2025-11-09T10:30:00Z',
  },
  {
    id_producto: 8,
    nombre: 'Donas Glaseadas',
    descrip: 'Donas frescas y suaves con glaseado de azúcar.',
    precio: 1.25,
    stock: 80,
    activo: true,
    createdAt: '2025-11-09T10:35:00Z',
  },
  {
    id_producto: 9,
    nombre: 'Pastel de Tres Leches',
    descrip: 'Pastel tradicional empapado en tres tipos de leche.',
    precio: 28.0,
    stock: 12,
    activo: true,
    createdAt: '2025-11-09T10:40:00Z',
  },
  {
    id_producto: 10,
    nombre: 'Muffins de Arándano',
    descrip: 'Muffins caseros con arándanos frescos.',
    precio: 2.75,
    stock: 45,
    activo: true,
    createdAt: '2025-11-09T10:45:00Z',
  },
  {
    id_producto: 11,
    nombre: 'Eclairs de Chocolate',
    descrip: 'Pastelitos rellenos de crema y cubiertos de chocolate.',
    precio: 4.0,
    stock: 30,
    activo: true,
    createdAt: '2025-11-09T10:50:00Z',
  },
  {
    id_producto: 12,
    nombre: 'Rollo de Canela',
    descrip: 'Rollo de canela caliente con glaseado de queso crema.',
    precio: 3.5,
    stock: 55,
    activo: true,
    createdAt: '2025-11-09T10:55:00Z',
  },
  {
    id_producto: 13,
    nombre: 'Gomitas de Frutas',
    descrip: 'Bolsa de 250g de gomitas de sabores frutales.',
    precio: 5.0,
    stock: 200,
    activo: true,
    createdAt: '2025-11-09T11:00:00Z',
  },
  {
    id_producto: 14,
    nombre: 'Paletas de Caramelo',
    descrip: 'Paletas de caramelo artesanales.',
    precio: 1.0,
    stock: 300,
    activo: true,
    createdAt: '2025-11-09T11:05:00Z',
  },
  {
    id_producto: 15,
    nombre: 'Bombones de Chocolate',
    descrip: 'Caja de 12 bombones de chocolate surtidos.',
    precio: 15.0,
    stock: 50,
    activo: true,
    createdAt: '2025-11-09T11:10:00Z',
  },
  {
    id_producto: 16,
    nombre: 'Flan Napolitano',
    descrip: 'Postre cremoso de flan con caramelo.',
    precio: 4.5,
    stock: 25,
    activo: true,
    createdAt: '2025-11-09T11:15:00Z',
  },
  {
    id_producto: 17,
    nombre: 'Merengues',
    descrip: 'Bolsa de merengues ligeros y crujientes.',
    precio: 3.0,
    stock: 70,
    activo: false,
    createdAt: '2025-11-09T11:20:00Z',
  },
  {
    id_producto: 18,
    nombre: 'Pastel de Zanahoria',
    descrip: 'Pastel de zanahoria con betún de queso crema.',
    precio: 22.0,
    stock: 18,
    activo: true,
    createdAt: '2025-11-09T11:25:00Z',
  },
  {
    id_producto: 19,
    nombre: 'Alfajores',
    descrip: 'Galletas suaves rellenas de dulce de leche.',
    precio: 2.0,
    stock: 90,
    activo: true,
    createdAt: '2025-11-09T11:30:00Z',
  },
  {
    id_producto: 20,
    nombre: 'Tiramisú',
    descrip: 'Postre italiano de café y crema.',
    precio: 6.0,
    stock: 22,
    activo: true,
    createdAt: '2025-11-09T11:35:00Z',
  },
];
